name: Scala CI

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  verilator:
    name: verilator regression
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Verilator
      run:  sudo apt-get install verilator
    - name: Setup Scala
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 11
        cache: 'sbt'
    - name: Test
      run: sbt test

